# Generated by Django 5.1.4 on 2025-04-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('email', models.CharField(default='', max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='uploads/')),
                ('birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('image', models.ImageField(default='', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('rno', models.IntegerField(default=0)),
                ('std', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=200)),
                ('city', models.CharField(choices=[('Ahemedabad', 'Ahemedabad'), ('Surendranagar', 'Surendranagar'), ('Surat', 'Surat'), ('Bhavnagar', 'Bhavnagar'), ('Gandhinagar', 'Gandhinagar')], default='Ahemaedabad', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='', upload_to='uploads/')),
                ('courses', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_paid', models.DateField()),
                ('take', models.CharField(max_length=50)),
                ('pay_method', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Card', 'Card')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='web.student')),
            ],
        ),
    ]
